CREATE TABLE IF NOT EXISTS ENROLLMENT (
	STUD_ID INTEGER UNSIGNED,
    CLASS_ID INTEGER UNSIGNED,
    ENROLL_STATUS VARCHAR(10) NOT NULL,
	ENROLL_SCORE DECIMAL(2, 1),
    ENROLL_DATE DATE NOT NULL,
    PRIMARY KEY (STUD_ID, CLASS_ID),
    FOREIGN KEY (STUD_ID) REFERENCES STUDENT (STUD_ID) ON DELETE CASCADE,
    FOREIGN KEY (CLASS_ID) REFERENCES CLASS (CLASS_ID) ON DELETE CASCADE
);

CREATE INDEX ENROLL_SCORE ON ENROLLMENT (ENROLL_SCORE);

/* notes
a student can take many classes and a class can be taken by many students
*/