CREATE TABLE IF NOT EXISTS ITEM (
	ITEM_ID INTEGER UNSIGNED AUTO_INCREMENT,
    ITEM_QTY SMALLINT NOT NULL,
    ROOM_NUM VARCHAR(3) NOT NULL,
    DEPT_CODE INTEGER UNSIGNED NOT NULL,
    INVT_CODE INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY (ITEM_ID),
    FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT (DEPT_CODE) ON UPDATE CASCADE,
    FOREIGN KEY (INVT_CODE) REFERENCES INVENTORY (INVT_CODE) ON UPDATE CASCADE
);

/*
item represents inventory being used outside of inventory.
this may be items in classrooms, cafeteria, etc.
*/