/* BUDGET TRIGGER */

DELIMITER //
CREATE TRIGGER BEFORE_INSERT_BUDGET
BEFORE INSERT ON BUDGET
FOR EACH ROW
BEGIN
    -- Set BUD_REMAIN to the value of BUD_ALLOCATED
    SET NEW.BUD_REMAIN = NEW.BUD_ALLOCATED;
END;
//
DELIMITER ;


DELIMITER //

CREATE TRIGGER BEFORE_UPDATE_BUDGET
BEFORE UPDATE ON BUDGET
FOR EACH ROW
BEGIN
    -- Only update BUD_REMAIN if BUD_ALLOCATED is being changed
    IF OLD.BUD_ALLOCATED != NEW.BUD_ALLOCATED THEN
        SET NEW.BUD_REMAIN = NEW.BUD_ALLOCATED;
    END IF;
END;
//

DELIMITER ;
