/* ITEM TRIGGER */

DELIMITER //
CREATE TRIGGER AFTER_UPDATE_ITEM
AFTER UPDATE ON ITEM
FOR EACH ROW
BEGIN
    -- Subtract the new ITEM_QTY from the corresponding INVENTORY item
    UPDATE INVENTORY
    SET INVT_QTY = INVT_QTY - (NEW.ITEM_QTY - OLD.ITEM_QTY)
    WHERE INVT_CODE = NEW.INVT_CODE;
END;
//
DELIMITER ;

DELIMITER //
CREATE TRIGGER AFTER_INSERT_ITEM
AFTER INSERT ON ITEM
FOR EACH ROW
BEGIN
    -- Subtract the ITEM_QTY from the corresponding INVENTORY item
    UPDATE INVENTORY
    SET INVT_QTY = INVT_QTY - NEW.ITEM_QTY
    WHERE INVT_CODE = NEW.INVT_CODE;
END;
//
DELIMITER ;


-- rare situation where the items are returned back to the inventory ONLY
DELIMITER //

CREATE TRIGGER AFTER_DELETE_ITEM
AFTER DELETE ON ITEM
FOR EACH ROW
BEGIN
    -- Add the ITEM_QTY of the deleted item back to the corresponding INVENTORY item
    UPDATE INVENTORY
    SET INVT_QTY = INVT_QTY + OLD.ITEM_QTY
    WHERE INVT_CODE = OLD.INVT_CODE;
END;
//

DELIMITER ;