CREATE TABLE IF NOT EXISTS CLASS (
	CLASS_ID INTEGER UNSIGNED AUTO_INCREMENT,
    CLASS_CAPACITY SMALLINT NOT NULL,
    CLASS_ROOM CHAR(3) NOT NULL,
    CLASS_BLDG_ROOM CHAR(1) NOT NULL,
    EMP_ID INTEGER UNSIGNED,
    COURSE_ID INTEGER UNSIGNED,
    PRIMARY KEY (CLASS_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID) ON UPDATE CASCADE,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID) ON UPDATE CASCADE
);

CREATE INDEX CLASS_CAPACITY ON CLASS (CLASS_CAPACITY);

ALTER TABLE CLASS
MODIFY CLASS_ROOM CHAR(3) NULL;

ALTER TABLE CLASS
MODIFY CLASS_BLDG_ROOM CHAR(1) NULL;

ALTER TABLE CLASS
MODIFY COURSE_ID INTEGER UNSIGNED NOT NULL;

/* notes 
a class emerges after a course is created.
if a class is a requirement, a course may generate at least one class
*/