CREATE TABLE IF NOT EXISTS DEPARTMENT (
	DEPT_CODE INTEGER UNSIGNED AUTO_INCREMENT,
    DEPT_NAME VARCHAR(50) NOT NULL,
    DEPT_DESC TEXT NOT NULL,
    EMP_ID INTEGER UNSIGNED,
    PRIMARY KEY (DEPT_CODE),
    CONSTRAINT DEPT_NAME UNIQUE (DEPT_NAME)
);

ALTER TABLE DEPARTMENT
ADD FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID) ON UPDATE CASCADE;

/* notes
a department is managed by an employee
a department cannot share the same name with another department.
*/