CREATE TABLE IF NOT EXISTS GUIDE (
	GUID_ID INTEGER UNSIGNED AUTO_INCREMENT,
    GUID_FNAME VARCHAR(20) NOT NULL,
    GUID_LNAME VARCHAR(20) NOT NULL,
    GUID_INITIAL CHAR(1),
    GUID_ADDRESS VARCHAR(150) NOT NULL,
    GUID_CITY VARCHAR(50) NOT NULL,
    GUID_PHONE VARCHAR(10) NOT NULL,
    GUID_EMAIL VARCHAR(50),
    PRIMARY KEY (GUID_ID)
);

CREATE INDEX GUID_NAME ON GUIDE(GUID_LNAME, GUID_FNAME);

/* notes
a guide is a person who overlooks a student.
a guide can be a parent, sibling, relative, etc.
*/