CREATE TABLE IF NOT EXISTS INVOICE (
	INV_ID INTEGER UNSIGNED AUTO_INCREMENT,
    INV_ISSUE_DATE DATE NOT NULL,
    INV_DUE_DATE DATE NOT NULL,
    INV_TOTAL_AMT DECIMAL(9, 2) NOT NULL,
    INV_PAY_STATUS VARCHAR(20) NOT NULL,
    DEPT_CODE INTEGER UNSIGNED,
    SUPP_ID INTEGER UNSIGNED,
    PRIMARY KEY (INV_ID),
    FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT (DEPT_CODE) ON UPDATE CASCADE,
    FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER (SUPP_ID) ON UPDATE CASCADE
);

CREATE INDEX INV_TOTAL_AMT ON INVOICE (INV_TOTAL_AMT);

/* notes
*/