CREATE TABLE IF NOT EXISTS STUDENT (
	STUD_ID INTEGER UNSIGNED AUTO_INCREMENT, 
    STUD_FNAME VARCHAR(20) NOT NULL,
    STUD_LNAME VARCHAR(20) NOT NULL,
    STUD_INITIAL CHAR(1),
    STUD_DOB DATE NOT NULL,
    STUD_ADDRESS VARCHAR(150) NOT NULL,
    STUD_CITY VARCHAR(50) NOT NULL,
    STUD_EMAIL VARCHAR(50),
    STUD_PHONE VARCHAR(10),
    STUD_ENROLL_DATE DATE NOT NULL,
    STUD_GRADE_LVL SMALLINT,
    STUD_GPA DECIMAL(2, 1),
    PRIMARY KEY(STUD_ID),
    CONSTRAINT GPA_CHK CHECK (STUD_GPA BETWEEN 0 AND 4) 
);

CREATE INDEX STUD_NAME ON STUDENT(STUD_LNAME, STUD_FNAME);
CREATE INDEX STUD_ENROLL_DATE ON STUDENT(STUD_ENROLL_DATE);
CREATE INDEX STUD_GPA ON STUDENT(STUD_GPA);

ALTER TABLE STUDENT
ADD CONSTRAINT STUD_GRADE_LVL CHECK (STUD_GRADE_LVL BETWEEN 9 AND 12);

ALTER TABLE STUDENT
MODIFY STUD_GPA DECIMAL(3, 2)

/* notes
a student must be between grades 9 to 12.
a student will be provided a school email after enrollment in the school.
a new student will not have a cumulative gpa until their first year.
*/