CREATE TABLE IF NOT EXISTS SUPPLIER (
	SUPP_ID INTEGER UNSIGNED AUTO_INCREMENT,
    SUPP_NAME VARCHAR(50) NOT NULL,
    SUPP_PHONE VARCHAR(10) NOT NULL,
    SUPP_EMAIL VARCHAR(50) NOT NULL,
    SUPP_ADDRESS VARCHAR(150) NOT NULL,
    SUPP_CITY VARCHAR(50) NOT NULL,
    SUPP_TYPE VARCHAR(25) NOT NULL,
    SUPP_CONT_START DATE NOT NULL,
    SUPP_CONT_END DATE NOT NULL,
    PRIMARY KEY (SUPP_ID),
    CONSTRAINT SUPP_NAME UNIQUE (SUPP_NAME)
);

/* note
a supplier cannot be entered twice or more; therefore, a unique constraint is placed
*/